### ISSUE TITLE
Tidy up homepage filters UI

### ISSUE THREAD

**Issue by zarino** [mysociety/contract-countdown#17]
@struan has implemented working Django filters at the top of the homepage, but they are lacking Bootstrap layout / styling classes.

<img width="798" alt="Screenshot 2022-09-22 at 09 20 06" src="https://user-images.githubusercontent.com/739624/191696326-36670b31-ae40-4ddb-b520-6561e749c17c.png">

**Comment by lucascumsille** [comment]
[Internal]Readability
https://baymard.com/blog/line-length-readability
