### ISSUE TITLE
DtypeWarning when running import_tenders

### ISSUE THREAD

**Issue by sagepe** [mysociety/contract-countdown#19]
When running `import_tenders`, we see the following warning that may or may not need action:

```
/app/procurement/management/commands/import_tenders.py:83: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(self.data_file)
```

**Comment by zarino** [comment]
Looks like the proper solution here is to pass a `dict` of column names and types as the `dtype` argument to `pd.read_csv()` in [`commands/import_tenders.py`](https://github.com/mysociety/contract-countdown/blob/911677d9ac0d66baf12e5af7f914414ad885e84e/procurement/management/commands/import_tenders.py#L83).

But there are 60 columns in the CSV, so not trivial to go through and specify a type for each. Any thoughts @struan @alexander-griffen ?

**Comment by alexander-griffen** [comment]
Another solution to this would be to set low_memory to false. This isn't the 'proper' solution, but would avoid going through each of the 60 columns. Historically, I've used this and it hasn't broken anything, I assume it would just make the import process use more memory. Could this become a problem if we're doing frequent data updates?

**Comment by alexander-griffen** [comment]
Closed, as tender_import script changed, and no longer produces this warning.
