### ISSUE TITLE
Establish feedback loops with potential users of Contract Countdown

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/contract-countdown#24]
We need to establish feedback loops to inform development - see [Contract Countdown – Plan for Alpha stage](https://docs.google.com/document/d/11t8fO2cnnQoZOD-MbZZmzieW4mvtFgcbrwCboC5exkE/edit?usp=sharing).

Aiming for at least 5 perspectives from each user group.

Calendar appointments are titled "Contract Countdown feedback call w/mySociety" and include Siôn & Zarino (ticked if completed):

**Climate officers**
- [x] 22/11/22 – Tom Taylor, Climate Policy and Research Officer @ Southwark Council
- [x] 23/11/22 – Claire Marion, Carbon Manager (Lead Change & Delivery Officer) @ The City of Edinburgh Council
- [x] 29/11/22 – Andrew Collins, Specialist Climate Emergency Officer @ Wokingham Borough Council
- [x] 13/01/23 – Donna Sibley, Sustainability and Climate Officer @ Torridge and North Devon District Council
- [ ] 13/01/23 – Olya K-Mehri, Senior Climate Change Officer @ Surrey County Council

**Journalists**
- [x] 22/11/22 – Lucas Amin, Investigative Journalist @ openDemocracy
- [x] 29/11/22 – Keith Magnum, Director @ Citizen News & Media Limited
- [x] 07/12/22 – David Thorpe, Freelance journalist @ The Fifth Estate
- [ ] 11/01/23 – Phil Creighton, Editor @ Reading Today & Wokingham Today
- [x] 16/12/22 – John Guinn, Local Democracy Reporter @ JPIMedia
- [ ] 13/01/23 – Bryan Rylands, Public Face & Editor @ The Shepway Vox

**Non Governmental-Organisations**
- [x] 22/11/22 – Robbie Gillett, Arts Director @ AdfreeCities
- [x] 28/11/22 – Shlomo Dowen, Coordinator @ UK Without Incineration Network
- [x] 12/12/22 – Lauren Griffiths, Digital Fundraising Manager @ Solar Aid
- [x] 13/01/23 – Colette Fox, Programme Manager @ ProVeg International
- [x] 11/01/23 – Ruth Westcott, Climate and Nature Emergency Co-ordinator @ Sustain

**Other**

- [x] 07/12/22 – Dr Anna Stegman, Local Energy Insights Manager @ Energy Systems Catapult

We could pay journalists for their time, and there's potential for a formal partnership as there's sub-grant budget available.

**Comment by JenMysoc** [comment]
**Dependencies:**

- [x] #11
- [x] #15
- [x] #7
- [x] #9

**Comment by drain-brain** [comment]
**Draft focus group format**

- 00-05 – Project history.
- 05-10 – Demo and explanation of what it is.
- 10-15 – Participants have time to play with it on their own.
- 15-55 – Series of questions.
- 55-60 – Wrap-up.

**Comment by drain-brain** [comment]
**Next steps:**

- [x] @sequencefree to establish if this ticket has an owner.
- [x] @sequencefree to discuss focus group design with @ajparsons eg. questions and theories to test, a plan for how to run.
- [ ] @sequencefree to speak to Society Works about how they run user groups.
- [ ] @sequencefree to think about any potential crossover with FMS/WDTK Pro.
- [x] @sequencefree to explore possibility of presenting at a [POGO Club](https://golab.bsg.ox.ac.uk/community/peer-learning-groups/pogo/) event.
- [x] @sequencefree to confirm date for contacting council officers with Climate Emergency UK.
- [x] @sequencefree to tailor [Template email for procurement outreach](https://docs.google.com/document/d/1sXLl6-_3d0csUiHPjYm3-_XMq7Dd_M0DX2fx1DD9AWQ/edit?usp=sharing) and save as template emails.
- [ ] @sequencefree to share in Collective for Climate Action Slack and raise in Councils Working Group meeting.
- [x] @sequencefree to consolidate and label stakeholders with Contract Countdown on [Outreach board](https://trello.com/b/YTOQJNTX/outreach).
- [ ] @sequencefree to send relevant email to stakeholders labelled with Contract Countdown on [Outreach board](https://trello.com/b/YTOQJNTX/outreach) and log in [Climate stakeholders spreadsheet](https://docs.google.com/spreadsheets/d/1MF5Bo9CaMFYDFlBugA9dwyxgRyHV9lOqCMggByQEuUY/edit?usp=sharing).
- [x] @sequencefree to consider approaching the following and asking for inclusion in newsletter: info@journalismfund.eu / mjarvis@transparency-initiative.org /  info@journalismfestival.com / reuters.institute@politics.ox.ac.uk / srccon@opennews.org / / meeseE@cardiff.ac.uk & abbottM2@cardiff.ac.uk / samantha@hackshackers.com / info@journalismfestival.com
- [x] @sequencefree to ensure [dependencies](https://github.com/mysociety/contract-countdown/issues/24#issuecomment-1259347120) are done before initiating feedback loops.

**Comment by drain-brain** [comment]
@zarino Are we only interested in feedback from UK-based journalists at this stage?

**Comment by zarino** [comment]
@sequencefree It’s unlikely we’ll expand to non-UK contracts data any time soon, but I guess it’s always interesting to know what sorts of things would potentially work in other countries. Which is a very non-committal way of saying, yes, I guess we _are_ sort of interested in non-UK feedback, if they can get over the fact that our alpha version is all very UK-centric.

**Comment by JenMysoc** [comment]
Just checking: all calls should be finished by now? And we're in the writing up phase (which will be a separate ticket)

**Comment by zarino** [comment]
@JenMysoc Yes!

**Comment by zarino** [comment]
Think we can close this now, in favour of https://github.com/mysociety/contract-countdown/issues/47 which covers deciding next steps.
