### ISSUE TITLE
Write summary doc describing contract countdown

### ISSUE THREAD

**Issue by struan** [mysociety/contract-countdown#27]
Something like the Local Intelligence Hub [plan for Beta document](https://docs.google.com/document/d/1QJ-Jdvg5CzPUtTmpl7lA8eSeYlQ1o8eu6BQK9Zsz5xQ/edit), rather than a tech spec.

- goals
- risks and mitigations
- timeline
- potential CAPE overlap

**Comment by JenMysoc** [comment]
Also:

- Specifics of what data we need
- Feedback loop scale/needs per group type
- What are the knowledge gaps and how do we need to fill them?
- Call to action: FOI/WTT councillors - social value, community organising/voice raising

**Comment by zarino** [comment]
I’ve made a start here: https://docs.google.com/document/d/11t8fO2cnnQoZOD-MbZZmzieW4mvtFgcbrwCboC5exkE/edit /cc @alexander-griffen @sequencefree

**Comment by zarino** [comment]
> I’ve made a start here: https://docs.google.com/document/d/11t8fO2cnnQoZOD-MbZZmzieW4mvtFgcbrwCboC5exkE/edit

Ok, @alexander-griffen @sequencefree I think this 👆 is ready for you to review. Does it help? Is there anything you’re still unsure about?

**Comment by zarino** [comment]
Closing this as everyone seems happy with the document so far. Can always expand it as new things come up 👍
