### ISSUE TITLE
Consider partnerships and user feedback loops

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/contract-countdown#28]
We need to get some user feedback loops going to ensure we're going in the right direction and building something useful. 

Some options we have thought about:

NGOs and council actors who might be interested in using this
User Feedback loop organisation - either specific individual users or focus groups or something else, linked to #24  
Or potentially a formal partnership. This is an option as we have subgrant budget here which we could spend.

**Comment by drain-brain** [comment]
**Next steps:**

- [x] @sequencefree to establish if this ticket has an owner.
- [ ] @sequencefree to discuss focus group design with @ajparsons.
- [ ] @sequencefree to cross-reference with https://github.com/mysociety/contract-countdown/issues/24 esp. checking relevance and status of [dependencies](https://github.com/mysociety/contract-countdown/issues/24#issuecomment-1259347120).
- [ ] @sequencefree to tailor [Template email for procurement outreach](https://docs.google.com/document/d/1sXLl6-_3d0csUiHPjYm3-_XMq7Dd_M0DX2fx1DD9AWQ/edit?usp=sharing) and send to relevant stakeholders labelled with Contract Countdown on [Outreach board](https://trello.com/b/YTOQJNTX/outreach).

**Comment by drain-brain** [comment]
Closed and folded description into overlapping ticket: https://github.com/mysociety/contract-countdown/issues/24
