### ISSUE TITLE
Filter contracts by postcode

### ISSUE THREAD

**Issue by zarino** [mysociety/contract-countdown#3]
Filter the list of contracts on the homepage by typing a postcode into a search box and submitting the form – like the one on https://data.climateemergency.uk/.

Once the form has been submitted, the homepage should show only contracts involving the council(s) that cover that postcode.

**Comment by struan** [comment]
At the moment the postcode box on the homepage goes to the council page for that postcode.

**Comment by struan** [comment]
And it now does the correct thing although lacks any error handling at the moment.

**Comment by zarino** [comment]
I think we can count this as done. You can filter by postcode. There are improvements that could be made to how postcode errors are handled, but let’s leave that to a different ticket (as it will also affect any other forms on the site).
