### ISSUE TITLE
Improve bootstrap form error handling across the site

### ISSUE THREAD

**Issue by zarino** [mysociety/contract-countdown#31]
The error handling for the postcode form is particularly odd.

We currently have `server_side_validation: False` in the `BOOTSTRAP5` settings, to hide the green "success" validation on valid fields … but that means we lack error styling for invalid fields. :-/

Needs some thinking about.

**Comment by alexander-griffen** [comment]
@zarino  - do you want to close this now, or I can make a PR to ensure `{% bootstrap_field FIELDNAME %}` is used everywhere across the site first?

**Comment by zarino** [comment]
> or I can make a PR to ensure {% bootstrap_field FIELDNAME %} is used everywhere across the site first?

@alexander-griffen that would be great, if it’s fairly quick to do.
