### ISSUE TITLE
Sort contracts by different criteria

### ISSUE THREAD

**Issue by zarino** [mysociety/contract-countdown#6]
Allow the list of contracts on the homepage to be sorted by any one of:

- [x] least time remaining (end time, ascending)
- [x] most time remaining (end time, descending)
- [x] longest duration (duration, descending)
- [x] shortest duration (duration, ascending)
- [x] highest total cost (cost, descending)
- [ ] highest estimated emissions (emissions, descending) – if we have that data

**Comment by struan** [comment]
Various of these need work to correctly handle null values and contracts that have ended.

**Comment by zarino** [comment]
We have most of this in place. Sorting by emissions estimates will be covered by https://github.com/mysociety/contract-countdown/issues/37.
