### ISSUE TITLE
Page for an individual contract

### ISSUE THREAD

**Issue by zarino** [mysociety/contract-countdown#7]
Will display the same info as in the list (#1) plus:

- [x] contract description
- [x] contract categories
- [x] actions (FOI guidance, and contact councillor)
- [x] case studies (hard-coded for now)

**Comment by zarino** [comment]
I wonder whether maybe @lucascumsille could check out the state of this page, and add in the actions and some (fake?) case studies, if they’re currently missing?

**Comment by zarino** [comment]
@alexander-griffen is implementing this page. Will need some review from @lucascumsille before it goes live.

**Comment by JenMysoc** [comment]
has this been implemented? does it need review?

**Comment by zarino** [comment]
PR https://github.com/mysociety/contract-countdown/pull/33 is just awaiting review and merge from @alexander-griffen.
